server:
  port: 8086

spring:
  application:
    name: notice-service
  config:
    import: optional:nacos:notice-service.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
